In [1]:
import pandas as pd

In [2]:
df1=pd.read_excel("world_population_excel_workbook.xlsx", sheet_name="Sheet1") #read_csv() doesnt necessarily mean that the file has to be .csv. it can be .txt and others too
pd.set_option('display.max.rows',150) #modifies global behaviour for all dataframes 
pd.set_option('display.min.rows',100)
df1

#Header is just what the columns are called. 
#If we say that the dataframe we imported has header=None (no header) then it automatically gives 0,1,2... indexing
#If not, it assumes it has headers and it will make the first row of data the header.
#We can also specify the names of the header we want. we say header=None, Names=[name1, name2, ...]
#Depending on how data is separated in the csv file, we choose our sep. 
#Country,Region,Population,Area
#Afghanistan,ASIA,31056997,647500
#Albania,EASTERN EUROPE,3581655,28748
#Algeria,NORTHERN AFRICA,32930091,2381740
#This is an example of how a CSV may look like. It is an example where data entries are separated by comma.
#If the csv file (or any format like .txt, etc) is actually comma separated and we set sep to something else other than "," then it treats the entire line in the csv file as one 
#single data entry.
#Alternatively, we can use read_table
#The difference is that for read_csv(), the sep is set to "," by default
#for read_txt(), the sep is set to "/t" by default
#also pd.read_json exists too. json is semistructured data
#There is also read_excel()


#Display.max.rows: Only show the whole table if no. of rows are smaller than this number
#Display.min.rows: Only matters if maxrows is triggered. If the table is too long, show only these many rows.

     Rank CCA3                       Country              Capital
0      36  AFG                   Afghanistan                Kabul
1     138  ALB                       Albania               Tirana
2      34  DZA                       Algeria              Algiers
3     213  ASM                American Samoa            Pago Pago
4     203  AND                       Andorra     Andorra la Vella
5      42  AGO                        Angola               Luanda
6     224  AIA                      Anguilla           The Valley
7     201  ATG           Antigua and Barbuda       Saint Johnâ€™s
8      33  ARG                     Argentina         Buenos Aires
9     140  ARM                       Armenia              Yerevan
10    198  ABW                         Aruba           Oranjestad
11     55  AUS                     Australia             Canberra
12     99  AUT                       Austria               Vienna
13     91  AZE                    Azerbaijan                 Baku
14    176  BHS                       Bahamas               Nassau
15    154  BHR                       Bahrain               Manama
16      8  BGD                    Bangladesh                Dhaka
17    186  BRB                      Barbados           Bridgetown
18     96  BLR                       Belarus                Minsk
19     81  BEL                       Belgium             Brussels
20    177  BLZ                        Belize             Belmopan
21     77  BEN                         Benin           Porto-Novo
22    206  BMU                       Bermuda             Hamilton
23    165  BTN                        Bhutan              Thimphu
24     80  BOL                       Bolivia                Sucre
25    137  BIH        Bosnia and Herzegovina             Sarajevo
26    144  BWA                      Botswana             Gaborone
27      7  BRA                        Brazil             Brasilia
28    221  VGB        British Virgin Islands            Road Town
29    175  BRN                        Brunei  Bandar Seri Begawan
30    108  BGR                      Bulgaria                Sofia
31     58  BFA                  Burkina Faso          Ouagadougou
32     78  BDI                       Burundi            Bujumbura
33     73  KHM                      Cambodia           Phnom Penh
34     53  CMR                      Cameroon              Yaounde
35     39  CAN                        Canada               Ottawa
36    171  CPV                    Cape Verde                Praia
37    205  CYM                Cayman Islands          George Town
38    117  CAF      Central African Republic               Bangui
39     69  TCD                          Chad            N'Djamena
40     65  CHL                         Chile             Santiago
41      1  CHN                         China              Beijing
42     28  COL                      Colombia               Bogota
43    163  COM                       Comoros               Moroni
44    223  COK                  Cook Islands               Avarua
45    124  CRI                    Costa Rica            San JosÃ©
46    130  HRV                       Croatia               Zagreb
47     85  CUB                          Cuba               Havana
48    189  CUW                       Curacao           Willemstad
49    158  CYP                        Cyprus              Nicosia
..    ...  ...                           ...                  ...
184   105  SRB                        Serbia             Belgrade
185   196  SYC                    Seychelles             Victoria
186   102  SLE                  Sierra Leone             Freetown
187   113  SGP                     Singapore            Singapore
188   214  SXM                  Sint Maarten          Philipsburg
189   116  SVK                      Slovakia           Bratislava
190   148  SVN                      Slovenia            Ljubljana
191   166  SLB               Solomon Islands              Honiara
192    70  SOM                       Somalia            Mogadishu
193    24  ZAF                  South Africa             Pretoria
194    29  KOR                   South Korea                Seoul
195    86  SSD                   South Sudan                 Juba
196    30  ESP                         Spain               Madrid
197    61  LKA                     Sri Lanka              Colombo
198    32  SDN                         Sudan             Khartoum
199   170  SUR                      Suriname           Paramaribo
200    87  SWE                        Sweden            Stockholm
201   101  CHE                   Switzerland                 Bern
202    60  SYR                         Syria             Damascus
203    57  TWN                        Taiwan               Taipei
204    95  TJK                    Tajikistan             Dushanbe
205    22  TZA                      Tanzania               Dodoma
206    20  THA                      Thailand              Bangkok
207   155  TLS                   Timor-Leste                 Dili
208   100  TGO                          Togo                LomÃ©
209   233  TKL                       Tokelau             Nukunonu
210   197  TON                         Tonga         Nukuâ€˜alofa
211   153  TTO           Trinidad and Tobago        Port-of-Spain
212    79  TUN                       Tunisia                Tunis
213    18  TUR                        Turkey               Ankara
214   111  TKM                  Turkmenistan             Ashgabat
215   212  TCA      Turks and Caicos Islands        Cockburn Town
216   227  TUV                        Tuvalu             Funafuti
217    31  UGA                        Uganda              Kampala
218    38  UKR                       Ukraine                 Kiev
219    97  ARE          United Arab Emirates            Abu Dhabi
220    21  GBR                United Kingdom               London
221     3  USA                 United States     Washington, D.C.
222   200  VIR  United States Virgin Islands     Charlotte Amalie
223   133  URY                       Uruguay           Montevideo
224    43  UZB                    Uzbekistan             Tashkent
225   181  VUT                       Vanuatu            Port-Vila
226   234  VAT                  Vatican City         Vatican City
227    51  VEN                     Venezuela              Caracas
228    16  VNM                       Vietnam                Hanoi
229   226  WLF             Wallis and Futuna             Mata-Utu
230   172  ESH                Western Sahara            El AaiÃºn
231    46  YEM                         Yemen                Sanaa
232    63  ZMB                        Zambia               Lusaka
233    74  ZWE                      Zimbabwe               Harare

[234 rows x 4 columns]

In [3]:
#Filtering columns and rows in pandas
df2=pd.read_csv("world_population.csv")
df2

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2.842321e+06,2.866849e+06,2.882481e+06,2.913399e+06,3.182021e+06,3.295066e+06,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,4.490322e+07,4.345167e+07,3.954315e+07,3.585634e+07,3.077462e+07,2.551807e+07,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,4.427300e+04,4.618900e+04,5.136800e+04,5.484900e+04,5.823000e+04,4.781800e+04,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,7.982400e+04,7.770000e+04,7.174600e+04,7.151900e+04,6.609700e+04,5.356900e+04,35611.0,19860.0,468.0,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,3.558899e+07,3.342848e+07,2.812772e+07,2.336418e+07,1.639406e+07,1.182864e+07,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,1.585700e+04,1.558500e+04,1.452500e+04,1.317200e+04,1.104700e+04,8.316000e+03,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint John’s,North America,9.376300e+04,9.266400e+04,8.994100e+04,8.569500e+04,7.505500e+04,6.332800e+04,64888.0,64516.0,442.0,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,4.551032e+07,4.503603e+07,4.325706e+07,4.110012e+07,3.707077e+07,3.263766e+07,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
9,140,ARM,Armenia,Yerevan,Asia,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
10,198,ABW,Aruba,Oranjestad,North America,1.064450e+05,1.065850e+05,1.042570e+05,1.003410e+05,8.910100e+04,6.571200e+04,62267.0,59106.0,180.0,591.3611,0.9991,0.00
11,55,AUS,Australia,Canberra,Oceania,2.617741e+07,2.567005e+07,2.382024e+07,2.201917e+07,1.901796e+07,1.704800e+07,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33
12,99,AUT,Austria,Vienna,Europe,8.939617e+06,8.907777e+06,8.642421e+06,8.362829e+06,8.010428e+06,7.678729e+06,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11
13,91,AZE,Azerbaijan,Baku,Asia,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
14,176,BHS,Bahamas,Nassau,North America,4.099840e+05,4.064710e+05,3.926970e+05,3.732720e+05,3.250140e+05,2.706790e+05,223752.0,179129.0,13943.0,29.4043,1.0051,0.01
15,154,BHR,Bahrain,Manama,Asia,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
17,186,BRB,Barbados,Bridgetown,North America,2.816350e+05,2.806930e+05,2.780830e+05,2.747110e+05,2.646570e+05,2.588680e+05,253575.0,241397.0,430.0,654.9651,1.0015,0.00
18,96,BLR,Belarus,Minsk,Europe,9.534954e+06,9.633740e+06,9.700609e+06,9.731427e+06,1.025648e+07,1.042852e+07,9817257.0,9170786.0,207600.0,45.9295,0.9955,0.12
19,81,BEL,Belgium,Brussels,Europe,1.165593e+07,1.156172e+07,1.124830e+07,1.087795e+07,1.026434e+07,9.959560e+06,9828986.0,9629376.0,30528.0,381.8111,1.0038,0.15
20,177,BLZ,Belize,Belmopan,North America,4.052720e+05,3.949210e+05,3.598710e+05,3.221060e+05,2.404060e+05,1.825890e+05,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
21,77,BEN,Benin,Porto-Novo,Africa,1.335286e+07,1.264312e+07,1.093278e+07,9.445710e+06,6.998023e+06,5.133419e+06,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
22,206,BMU,Bermuda,Hamilton,North America,6.418400e+04,6.403100e+04,6.314400e+04,6.344700e+04,6.137100e+04,5.747000e+04,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
23,165,BTN,Bhutan,Thimphu,Asia,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
24,80,BOL,Bolivia,Sucre,South America,1.222411e+07,1.193616e+07,1.109008e+07,1.022327e+07,8.592656e+06,7.096194e+06,5736088.0,4585693.0,1098581.0,11.1272,1.0120,0.15
25,137,BIH,Bosnia and Herzegovina,Sarajevo,Europe,3.233526e+06,3.318407e+06,3.524324e+06,3.811088e+06,4.179350e+06,4.494310e+06,4199820.0,3815561.0,51209.0,63.1437,0.9886,0.04
26,144,BWA,Botswana,Gaborone,Africa,2.630296e+06,2.546402e+06,2.305171e+06,2.091664e+06,1.726985e+06,1.341474e+06,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
28,221,VGB,British Virgin Islands,Road Town,North America,3.130500e+04,3.091000e+04,2.936600e+04,2.755600e+04,2.010400e+04,1.561700e+04,11109.0,9581.0,151.0,207.3179,1.0059,0.00
29,175,BRN,Brunei,Bandar Seri Begawan,Asia,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
30,108,BGR,Bulgaria,Sofia,Europe,6.781953e+06,6.979175e+06,7.309253e+06,7.592273e+06,8.097691e+06,8.767778e+06,8980606.0,8582950.0,110879.0,61.1654,0.9849,0.09
31,58,BFA,Burkina Faso,Ouagadougou,Africa,2.267376e+07,2.152263e+07,1.871802e+07,1.611684e+07,1.188289e+07,9.131361e+06,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
32,78,BDI,Burundi,Bujumbura,Africa,1.288958e+07,1.222023e+07,1.072715e+07,9.126605e+06,6.307659e+06,5.483793e+06,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
33,73,KHM,Cambodia,Phnom Penh,Asia,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
34,53,CMR,Cameroon,Yaounde,Africa,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
35,39,CAN,Canada,Ottawa,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
36,171,CPV,Cape Verde,Praia,Africa,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
37,205,CYM,Cayman Islands,George Town,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
38,117,CAF,Central African Republic,Bangui,Africa,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,1.772332e+07,1.664470e+07,1.414027e+07,1.189473e+07,8.259137e+06,5.827069e+06,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
40,65,CHL,Chile,Santiago,South America,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
42,28,COL,Colombia,Bogota,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
43,163,COM,Comoros,Moroni,Africa,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
44,223,COK,Cook Islands,Avarua,Oceania,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00
45,124,CRI,Costa Rica,San José,North America,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
46,130,HRV,Croatia,Zagreb,Europe,4.030358e+06,4.096868e+06,4.254815e+06,4.368682e+06,4.548434e+06,4.873707e+06,4680144.0,4492638.0,56594.0,71.2153,0.9927,0.05
47,85,CUB,Cuba,Havana,North America,1.121219e+07,1.130070e+07,1.133989e+07,1.129042e+07,1.110579e+07,1.062668e+07,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14
48,189,CUW,Curacao,Willemstad,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
49,158,CYP,Cyprus,Nicosia,Europe,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,105,SRB,Serbia,Belgrade,Europe,7.221365e+06,7.358005e+06,7.519496e+06,7.653748e+06,7.935022e+06,7.987529e+06,7777010.0,7193533.0,88361.0,81.7257,0.9897,0.09
185,196,SYC,Seychelles,Victoria,Africa,1.071180e+05,1.055300e+05,9.924000e+04,9.240900e+04,8.006000e+04,7.105700e+04,65290.0,54379.0,452.0,236.9867,1.0061,0.00
186,102,SLE,Sierra Leone,Freetown,Africa,8.605718e+06,8.233969e+06,7.314773e+06,6.436698e+06,4.584067e+06,4.325388e+06,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
187,113,SGP,Singapore,Singapore,Asia,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
188,214,SXM,Sint Maarten,Philipsburg,North America,4.417500e+04,4.362100e+04,4.020500e+04,3.303400e+04,3.048900e+04,2.784500e+04,12243.0,6260.0,34.0,1299.2647,1.0030,0.00
189,116,SVK,Slovakia,Bratislava,Europe,5.643453e+06,5.456681e+06,5.424444e+06,5.396424e+06,5.376690e+06,5.261305e+06,4973883.0,4522867.0,49037.0,115.0856,1.0359,0.07
190,148,SVN,Slovenia,Ljubljana,Europe,2.119844e+06,2.117641e+06,2.080862e+06,2.057286e+06,1.984339e+06,1.986024e+06,1901570.0,1741286.0,20273.0,104.5649,1.0002,0.03
191,166,SLB,Solomon Islands,Honiara,Oceania,7.242730e+05,6.911910e+05,6.126600e+05,5.403940e+05,4.299780e+05,3.241710e+05,233668.0,172833.0,28896.0,25.0648,1.0232,0.01
192,70,SOM,Somalia,Mogadishu,Africa,1.759751e+07,1.653702e+07,1.376391e+07,1.202665e+07,8.721465e+06,6.999096e+06,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
193,24,ZAF,South Africa,Pretoria,Africa,5.989388e+07,5.880193e+07,5.587650e+07,5.178492e+07,4.681327e+07,3.987757e+07,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
194,29,KOR,South Korea,Seoul,Asia,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
195,86,SSD,South Sudan,Juba,Africa,1.091316e+07,1.060623e+07,1.119430e+07,NaN,6.114440e+06,4.750817e+06,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
196,30,ESP,Spain,Madrid,Europe,4.755863e+07,4.736381e+07,4.643134e+07,4.657277e+07,4.074165e+07,3.888989e+07,37491666.0,33792617.0,505992.0,93.9909,1.0015,0.60
197,61,LKA,Sri Lanka,Colombo,Asia,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
198,32,SDN,Sudan,Khartoum,Africa,4.687420e+07,4.444049e+07,3.817118e+07,3.373993e+07,2.629877e+07,2.109089e+07,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
199,170,SUR,Suriname,Paramaribo,South America,6.180400e+05,6.070650e+05,5.754750e+05,5.460800e+05,4.789980e+05,4.127560e+05,375112.0,379918.0,163820.0,3.7727,1.0082,0.01
200,87,SWE,Sweden,Stockholm,Europe,1.054935e+07,1.036897e+07,9.849349e+06,9.381729e+06,8.871043e+06,8.548406e+06,8311763.0,8027702.0,450295.0,23.4276,1.0079,0.13
201,101,CHE,Switzerland,Bern,Europe,8.740472e+06,8.638613e+06,8.281732e+06,7.822435e+06,7.182059e+06,6.711693e+06,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
202,60,SYR,Syria,Damascus,Asia,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
203,57,TWN,Taiwan,Taipei,Asia,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
204,95,TJK,Tajikistan,Dushanbe,Asia,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
205,22,TZA,Tanzania,Dodoma,Africa,6.549775e+07,6.170452e+07,5.254282e+07,4.511053e+07,3.446370e+07,2.620601e+07,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
206,20,THA,Thailand,Bangkok,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
207,155,TLS,Timor-Leste,Dili,Asia,NaN,1.299995e+06,1.205813e+06,1.088486e+06,NaN,7.581060e+05,642224.0,554021.0,14874.0,90.1772,1.0154,0.02
208,100,TGO,Togo,Lomé,Africa,8.848699e+06,8.442580e+06,7.473229e+06,6.571855e+06,5.008035e+06,3.875947e+06,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
209,233,TKL,Tokelau,Nukunonu,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
210,197,TON,Tonga,Nuku‘alofa,Oceania,1.068580e+05,1.052540e+05,1.061220e+05,1.073830e+05,1.026030e+05,9.872700e+04,96708.0,86484.0,747.0,143.0495,1.0079,0.00
211,153,TTO,Trinidad and Tobago,Port-of-Spain,North America,1.531044e+06,1.518147e+06,1.460177e+06,1.410296e+06,1.332203e+06,1.266518e+06,1127852.0,988890.0,5130.0,NaN,1.0035,0.02
212,79,TUN,Tunisia,Tunis,Africa,1.235612e+07,1.216172e+07,1.155778e+07,1.089506e+07,9.893316e+06,8.440023e+06,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
213,18,TUR,Turkey,Ankara,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
214,111,TKM,Turkmenistan,Ashgabat,Asia,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
215,212,TCA,Turks and Caicos Islands,Cockburn Town,North America,4.570300e+04,4.427600e+04,3.653800e+04,2.972600e+04,1.874400e+04,1.170900e+04,7598.0,5665.0,948.0,48.2099,1.0131,0.00
216,227,TUV,Tuvalu,Funafuti,Oceania,1.131200e+04,1.106900e+04,1.087700e+04,1.055000e+04,9.638000e+03,9.182000e+03,7731.0,5814.0,26.0,435.0769,1.0096,0.00
217,31,UGA,Uganda,Kampala,Africa,4.724958e+07,4.440461e+07,3.747736e+07,3.234173e+07,2.402070e+07,1.758663e+07,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
218,38,UKR,Ukraine,Kiev,Europe,3.970174e+07,4.390967e+07,4.498256e+07,4.568302e+07,4.887976e+07,5.158982e+07,49973920.0,47279086.0,603500.0,65.7858,0.9120,0.50
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,6.750894e+07,6.705947e+07,6.522436e+07,6.276004e+07,5.885004e+07,5.721044e+07,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,9.946500e+04,1.004420e+05,1.028030e+05,1.061420e+05,1.081850e+05,1.006850e+05,96640.0,63446.0,347.0,286.6427,0.9937,0.00
223,133,URY,Uruguay,Montevideo,South America,3.422794e+06,3.429086e+06,3.402818e+06,3.352651e+06,3.292224e+06,3.117012e+06,2953750.0,2790265.0,181034.0,18.9069,0.9990,0.04
224,43,UZB,Uzbekistan,Tashkent,Asia,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
225,181,VUT,Vanuatu,Port-Vila,Oceania,3.267400e+05,3.116850e+05,2.764380e+05,2.454530e+05,1.920740e+05,1.508820e+05,118156.0,87019.0,12189.0,26.8061,1.0238,0.00
226,234,VAT,Vatican City,Vatican City,Europe,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,733.0,752.0,1.0,510.0000,0.9980,0.00
227,51,VEN,Venezuela,Caracas,South America,2.830170e+07,2.849045e+07,3.052972e+07,2.871502e+07,NaN,1.975058e+07,15210443.0,11355475.0,NaN,30.8820,1.0036,0.35
228,16,VNM,Vietnam,Hanoi,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,1.157200e+04,1.165500e+04,1.218200e+04,1.314200e+04,1.472300e+04,1.345400e+04,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,5.759860e+05,5.560480e+05,4.918240e+05,4.132960e+05,2.703750e+05,1.785290e+05,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,2.001768e+07,1.892772e+07,NaN,1.379209e+07,9.891136e+06,7.686401e+06,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,1.632054e+07,1.566967e+07,1.415494e+07,1.283977e+07,1.183468e+07,1.011389e+07,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [4]:
specific_countries=["Bangladesh","Brazil"]
df2[df2["Country"].isin(specific_countries)]

df2[df2["2022 Population"]>df2["2020 Population"]]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
2,34,DZA,Algeria,Algiers,Africa,4.490322e+07,4.345167e+07,3.954315e+07,3.585634e+07,3.077462e+07,2.551807e+07,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
4,203,AND,Andorra,Andorra la Vella,Europe,7.982400e+04,7.770000e+04,7.174600e+04,7.151900e+04,6.609700e+04,5.356900e+04,35611.0,19860.0,468.0,170.5641,1.0100,0.00
5,42,AGO,Angola,Luanda,Africa,3.558899e+07,3.342848e+07,2.812772e+07,2.336418e+07,1.639406e+07,1.182864e+07,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
6,224,AIA,Anguilla,The Valley,North America,1.585700e+04,1.558500e+04,1.452500e+04,1.317200e+04,1.104700e+04,8.316000e+03,6560.0,6283.0,91.0,174.2527,1.0066,0.00
7,201,ATG,Antigua and Barbuda,Saint John’s,North America,9.376300e+04,9.266400e+04,8.994100e+04,8.569500e+04,7.505500e+04,6.332800e+04,64888.0,64516.0,442.0,212.1335,1.0058,0.00
8,33,ARG,Argentina,Buenos Aires,South America,4.551032e+07,4.503603e+07,4.325706e+07,4.110012e+07,3.707077e+07,3.263766e+07,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
11,55,AUS,Australia,Canberra,Oceania,2.617741e+07,2.567005e+07,2.382024e+07,2.201917e+07,1.901796e+07,1.704800e+07,14706322.0,12595034.0,7692024.0,3.4032,1.0099,0.33
12,99,AUT,Austria,Vienna,Europe,8.939617e+06,8.907777e+06,8.642421e+06,8.362829e+06,8.010428e+06,7.678729e+06,7547561.0,7465301.0,83871.0,106.5877,1.0020,0.11
14,176,BHS,Bahamas,Nassau,North America,4.099840e+05,4.064710e+05,3.926970e+05,3.732720e+05,3.250140e+05,2.706790e+05,223752.0,179129.0,13943.0,29.4043,1.0051,0.01
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
17,186,BRB,Barbados,Bridgetown,North America,2.816350e+05,2.806930e+05,2.780830e+05,2.747110e+05,2.646570e+05,2.588680e+05,253575.0,241397.0,430.0,654.9651,1.0015,0.00
19,81,BEL,Belgium,Brussels,Europe,1.165593e+07,1.156172e+07,1.124830e+07,1.087795e+07,1.026434e+07,9.959560e+06,9828986.0,9629376.0,30528.0,381.8111,1.0038,0.15
20,177,BLZ,Belize,Belmopan,North America,4.052720e+05,3.949210e+05,3.598710e+05,3.221060e+05,2.404060e+05,1.825890e+05,145133.0,120905.0,22966.0,17.6466,1.0131,0.01
21,77,BEN,Benin,Porto-Novo,Africa,1.335286e+07,1.264312e+07,1.093278e+07,9.445710e+06,6.998023e+06,5.133419e+06,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
22,206,BMU,Bermuda,Hamilton,North America,6.418400e+04,6.403100e+04,6.314400e+04,6.344700e+04,6.137100e+04,5.747000e+04,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
23,165,BTN,Bhutan,Thimphu,Asia,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
24,80,BOL,Bolivia,Sucre,South America,1.222411e+07,1.193616e+07,1.109008e+07,1.022327e+07,8.592656e+06,7.096194e+06,5736088.0,4585693.0,1098581.0,11.1272,1.0120,0.15
26,144,BWA,Botswana,Gaborone,Africa,2.630296e+06,2.546402e+06,2.305171e+06,2.091664e+06,1.726985e+06,1.341474e+06,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
28,221,VGB,British Virgin Islands,Road Town,North America,3.130500e+04,3.091000e+04,2.936600e+04,2.755600e+04,2.010400e+04,1.561700e+04,11109.0,9581.0,151.0,207.3179,1.0059,0.00
29,175,BRN,Brunei,Bandar Seri Begawan,Asia,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
31,58,BFA,Burkina Faso,Ouagadougou,Africa,2.267376e+07,2.152263e+07,1.871802e+07,1.611684e+07,1.188289e+07,9.131361e+06,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
32,78,BDI,Burundi,Bujumbura,Africa,1.288958e+07,1.222023e+07,1.072715e+07,9.126605e+06,6.307659e+06,5.483793e+06,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
33,73,KHM,Cambodia,Phnom Penh,Asia,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
34,53,CMR,Cameroon,Yaounde,Africa,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
35,39,CAN,Canada,Ottawa,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
36,171,CPV,Cape Verde,Praia,Africa,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
37,205,CYM,Cayman Islands,George Town,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
38,117,CAF,Central African Republic,Bangui,Africa,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,1.772332e+07,1.664470e+07,1.414027e+07,1.189473e+07,8.259137e+06,5.827069e+06,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
40,65,CHL,Chile,Santiago,South America,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
42,28,COL,Colombia,Bogota,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
43,163,COM,Comoros,Moroni,Africa,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
45,124,CRI,Costa Rica,San José,North America,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
48,189,CUW,Curacao,Willemstad,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
49,158,CYP,Cyprus,Nicosia,Europe,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
51,115,DNK,Denmark,Copenhagen,Europe,5.882261e+06,5.825641e+06,5.677796e+06,5.550849e+06,5.340655e+06,5.144623e+06,5125392.0,4922963.0,43094.0,136.4984,1.0048,0.07
52,160,DJI,Djibouti,Djibouti,Africa,1.120849e+06,1.090156e+06,1.006259e+06,9.191990e+05,7.420330e+05,5.771730e+05,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
53,204,DMA,Dominica,Roseau,North America,7.273700e+04,7.199500e+04,7.000700e+04,6.875500e+04,6.834600e+04,6.948100e+04,72978.0,68895.0,751.0,96.8535,1.0045,0.00
54,84,DOM,Dominican Republic,Santo Domingo,North America,1.122882e+07,1.099966e+07,1.040583e+07,9.775755e+06,8.540791e+06,7.129004e+06,5755800.0,4475871.0,48671.0,230.7087,1.0100,0.14
55,15,COD,DR Congo,Kinshasa,Africa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
56,67,ECU,Ecuador,Quito,South America,1.800100e+07,1.758860e+07,1.619590e+07,1.498958e+07,1.262651e+07,1.044984e+07,8135845.0,6172215.0,276841.0,65.0229,1.0114,0.23
57,14,EGY,Egypt,Cairo,Africa,1.109901e+08,1.074651e+08,9.772380e+07,8.725241e+07,7.137137e+07,5.721463e+07,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
58,112,SLV,El Salvador,San Salvador,North America,6.336392e+06,6.292731e+06,6.231066e+06,6.114034e+06,5.958482e+06,5.367179e+06,4508992.0,3619090.0,21041.0,301.1450,1.0035,0.08
59,152,GNQ,Equatorial Guinea,Malabo,Africa,1.674908e+06,1.596049e+06,NaN,1.094524e+06,6.849770e+05,4.655490e+05,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
60,132,ERI,Eritrea,Asmara,Africa,3.684032e+06,3.555868e+06,3.340006e+06,3.147727e+06,2.392880e+06,2.149960e+06,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
63,12,ETH,Ethiopia,Addis Ababa,Africa,1.233799e+08,1.171909e+08,1.024719e+08,8.923779e+07,6.703187e+07,4.787807e+07,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
64,231,FLK,Falkland Islands,Stanley,South America,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170,64,ROU,Romania,Bucharest,Europe,1.965927e+07,1.944204e+07,1.990608e+07,2.033521e+07,2.191988e+07,2.283623e+07,22125224.0,19922618.0,238391.0,82.4665,1.0171,0.25
172,76,RWA,Rwanda,Kigali,Africa,1.377670e+07,1.314636e+07,1.164296e+07,1.030903e+07,8.109989e+06,7.319962e+06,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
173,228,BLM,Saint Barthelemy,Gustavia,North America,1.096700e+04,1.068100e+04,9.643000e+03,8.988000e+03,7.082000e+03,5.168000e+03,2983.0,2417.0,21.0,522.2381,1.0098,0.00
174,211,KNA,Saint Kitts and Nevis,Basseterre,North America,4.765700e+04,4.764200e+04,4.779000e+04,4.740300e+04,4.546100e+04,4.063600e+04,43097.0,44968.0,261.0,182.5939,1.0011,0.00
175,190,LCA,Saint Lucia,Castries,North America,1.798570e+05,1.792370e+05,1.756230e+05,1.709350e+05,1.595000e+05,1.423010e+05,121633.0,103090.0,616.0,291.9756,1.0011,0.00
179,188,WSM,Samoa,Apia,Oceania,2.223820e+05,2.149290e+05,2.035710e+05,1.946720e+05,1.840080e+05,1.681860e+05,164905.0,142771.0,2842.0,78.2484,1.0165,0.00
181,187,STP,Sao Tome and Principe,São Tomé,Africa,2.273800e+05,2.186410e+05,2.011240e+05,1.821380e+05,1.437140e+05,1.203430e+05,97210.0,77583.0,964.0,235.8714,1.0192,0.00
182,41,SAU,Saudi Arabia,Riyadh,Asia,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
183,72,SEN,Senegal,Dakar,Africa,1.731645e+07,1.643612e+07,1.435618e+07,1.253012e+07,9.704287e+06,7.536001e+06,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
185,196,SYC,Seychelles,Victoria,Africa,1.071180e+05,1.055300e+05,9.924000e+04,9.240900e+04,8.006000e+04,7.105700e+04,65290.0,54379.0,452.0,236.9867,1.0061,0.00
186,102,SLE,Sierra Leone,Freetown,Africa,8.605718e+06,8.233969e+06,7.314773e+06,6.436698e+06,4.584067e+06,4.325388e+06,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
187,113,SGP,Singapore,Singapore,Asia,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
188,214,SXM,Sint Maarten,Philipsburg,North America,4.417500e+04,4.362100e+04,4.020500e+04,3.303400e+04,3.048900e+04,2.784500e+04,12243.0,6260.0,34.0,1299.2647,1.0030,0.00
189,116,SVK,Slovakia,Bratislava,Europe,5.643453e+06,5.456681e+06,5.424444e+06,5.396424e+06,5.376690e+06,5.261305e+06,4973883.0,4522867.0,49037.0,115.0856,1.0359,0.07
190,148,SVN,Slovenia,Ljubljana,Europe,2.119844e+06,2.117641e+06,2.080862e+06,2.057286e+06,1.984339e+06,1.986024e+06,1901570.0,1741286.0,20273.0,104.5649,1.0002,0.03
191,166,SLB,Solomon Islands,Honiara,Oceania,7.242730e+05,6.911910e+05,6.126600e+05,5.403940e+05,4.299780e+05,3.241710e+05,233668.0,172833.0,28896.0,25.0648,1.0232,0.01
192,70,SOM,Somalia,Mogadishu,Africa,1.759751e+07,1.653702e+07,1.376391e+07,1.202665e+07,8.721465e+06,6.999096e+06,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
193,24,ZAF,South Africa,Pretoria,Africa,5.989388e+07,5.880193e+07,5.587650e+07,5.178492e+07,4.681327e+07,3.987757e+07,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
195,86,SSD,South Sudan,Juba,Africa,1.091316e+07,1.060623e+07,1.119430e+07,NaN,6.114440e+06,4.750817e+06,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
196,30,ESP,Spain,Madrid,Europe,4.755863e+07,4.736381e+07,4.643134e+07,4.657277e+07,4.074165e+07,3.888989e+07,37491666.0,33792617.0,505992.0,93.9909,1.0015,0.60
197,61,LKA,Sri Lanka,Colombo,Asia,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
198,32,SDN,Sudan,Khartoum,Africa,4.687420e+07,4.444049e+07,3.817118e+07,3.373993e+07,2.629877e+07,2.109089e+07,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
199,170,SUR,Suriname,Paramaribo,South America,6.180400e+05,6.070650e+05,5.754750e+05,5.460800e+05,4.789980e+05,4.127560e+05,375112.0,379918.0,163820.0,3.7727,1.0082,0.01
200,87,SWE,Sweden,Stockholm,Europe,1.054935e+07,1.036897e+07,9.849349e+06,9.381729e+06,8.871043e+06,8.548406e+06,8311763.0,8027702.0,450295.0,23.4276,1.0079,0.13
201,101,CHE,Switzerland,Bern,Europe,8.740472e+06,8.638613e+06,8.281732e+06,7.822435e+06,7.182059e+06,6.711693e+06,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
202,60,SYR,Syria,Damascus,Asia,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
203,57,TWN,Taiwan,Taipei,Asia,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
204,95,TJK,Tajikistan,Dushanbe,Asia,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
205,22,TZA,Tanzania,Dodoma,Africa,6.549775e+07,6.170452e+07,5.254282e+07,4.511053e+07,3.446370e+07,2.620601e+07,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
206,20,THA,Thailand,Bangkok,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
208,100,TGO,Togo,Lomé,Africa,8.848699e+06,8.442580e+06,7.473229e+06,6.571855e+06,5.008035e+06,3.875947e+06,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
209,233,TKL,Tokelau,Nukunonu,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
210,197,TON,Tonga,Nuku‘alofa,Oceania,1.068580e+05,1.052540e+05,1.061220e+05,1.073830e+05,1.026030e+05,9.872700e+04,96708.0,86484.0,747.0,143.0495,1.0079,0.00
211,153,TTO,Trinidad and Tobago,Port-of-Spain,North America,1.531044e+06,1.518147e+06,1.460177e+06,1.410296e+06,1.332203e+06,1.266518e+06,1127852.0,988890.0,5130.0,NaN,1.0035,0.02
212,79,TUN,Tunisia,Tunis,Africa,1.235612e+07,1.216172e+07,1.155778e+07,1.089506e+07,9.893316e+06,8.440023e+06,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
213,18,TUR,Turkey,Ankara,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
214,111,TKM,Turkmenistan,Ashgabat,Asia,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
215,212,TCA,Turks and Caicos Islands,Cockburn Town,North America,4.570300e+04,4.427600e+04,3.653800e+04,2.972600e+04,1.874400e+04,1.170900e+04,7598.0,5665.0,948.0,48.2099,1.0131,0.00
216,227,TUV,Tuvalu,Funafuti,Oceania,1.131200e+04,1.106900e+04,1.087700e+04,1.055000e+04,9.638000e+03,9.182000e+03,7731.0,5814.0,26.0,435.0769,1.0096,0.00
217,31,UGA,Uganda,Kampala,Africa,4.724958e+07,4.440461e+07,3.747736e+07,3.234173e+07,2.402070e+07,1.758663e+07,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,6.750894e+07,6.705947e+07,6.522436e+07,6.276004e+07,5.885004e+07,5.721044e+07,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
224,43,UZB,Uzbekistan,Tashkent,Asia,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
225,181,VUT,Vanuatu,Port-Vila,Oceania,3.267400e+05,3.116850e+05,2.764380e+05,2.454530e+05,1.920740e+05,1.508820e+05,118156.0,87019.0,12189.0,26.8061,1.0238,0.00
228,16,VNM,Vietnam,Hanoi,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
230,172,ESH,Western Sahara,El Aaiún,Africa,5.759860e+05,5.560480e+05,4.918240e+05,4.132960e+05,2.703750e+05,1.785290e+05,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,2.001768e+07,1.892772e+07,NaN,1.379209e+07,9.891136e+06,7.686401e+06,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,1.632054e+07,1.566967e+07,1.415494e+07,1.283977e+07,1.183468e+07,1.011389e+07,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [5]:
df2=df2.set_index("Country")
df2.filter(like="stan", axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Kazakhstan,66,KAZ,Nursultan,Asia,19397998.0,18979243.0,17835909.0,16627837.0,15236253.0,16866563.0,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
Kyrgyzstan,110,KGZ,Bishkek,Asia,6630623.0,6424874.0,5914980.0,5483774.0,4935182.0,4394734.0,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
Pakistan,5,PAK,Islamabad,Asia,235824862.0,227196741.0,210969298.0,194454498.0,154369924.0,115414069.0,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
Tajikistan,95,TJK,Dushanbe,Asia,9952787.0,9543207.0,8524063.0,7621779.0,6272998.0,5417860.0,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
Turkmenistan,111,TKM,Ashgabat,Asia,6430770.0,6250438.0,5766431.0,5267970.0,4569132.0,3720278.0,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
Uzbekistan,43,UZB,Tashkent,Asia,34627652.0,33526656.0,30949417.0,28614227.0,24925554.0,20579100.0,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43

In [6]:
df2.loc["United States"]

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

In [7]:
df2.iloc[3]

Rank                                 213
CCA3                                 ASM
Capital                        Pago Pago
Continent                        Oceania
2022 Population                  44273.0
2020 Population                  46189.0
2015 Population                  51368.0
2010 Population                  54849.0
2000 Population                  58230.0
1990 Population                  47818.0
1980 Population                  32886.0
1970 Population                  27075.0
Area (km²)                         199.0
Density (per km²)               222.4774
Growth Rate                       0.9831
World Population Percentage          0.0
Name: American Samoa, dtype: object

In [18]:
df2.sort_values(by=["Rank"], ascending=[True])

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
China,1,CHN,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
India,2,IND,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
United States,3,USA,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
Indonesia,4,IDN,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
Pakistan,5,PAK,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
Nigeria,6,NGA,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Brazil,7,BRA,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
Bangladesh,8,BGD,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
Russia,9,RUS,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
Mexico,10,MEX,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
Japan,11,JPN,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
Ethiopia,12,ETH,Addis Ababa,Africa,1.233799e+08,1.171909e+08,1.024719e+08,8.923779e+07,6.703187e+07,4.787807e+07,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Philippines,13,PHL,Manila,Asia,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
Egypt,14,EGY,Cairo,Africa,1.109901e+08,1.074651e+08,9.772380e+07,8.725241e+07,7.137137e+07,5.721463e+07,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
DR Congo,15,COD,Kinshasa,Africa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Vietnam,16,VNM,Hanoi,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
Iran,17,IRN,Tehran,Asia,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
Turkey,18,TUR,Ankara,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
Germany,19,DEU,Berlin,Europe,8.336984e+07,8.332899e+07,8.207323e+07,8.132509e+07,8.155168e+07,7.937020e+07,77786703.0,78294583.0,357114.0,233.4544,0.9995,1.05
Thailand,20,THA,Bangkok,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
United Kingdom,21,GBR,London,Europe,6.750894e+07,6.705947e+07,6.522436e+07,6.276004e+07,5.885004e+07,5.721044e+07,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
Tanzania,22,TZA,Dodoma,Africa,6.549775e+07,6.170452e+07,5.254282e+07,4.511053e+07,3.446370e+07,2.620601e+07,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
France,23,FRA,Paris,Europe,6.462663e+07,6.448005e+07,6.380977e+07,6.244457e+07,5.866545e+07,5.641290e+07,53713830.0,50523586.0,551695.0,117.1419,1.0015,0.81
South Africa,24,ZAF,Pretoria,Africa,5.989388e+07,5.880193e+07,5.587650e+07,5.178492e+07,4.681327e+07,3.987757e+07,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
Italy,25,ITA,Rome,Europe,5.903747e+07,5.950058e+07,6.023291e+07,5.982245e+07,5.696640e+07,5.675656e+07,56329482.0,53324036.0,301336.0,195.9191,0.9966,0.74
Myanmar,26,MMR,Nay Pyi Taw,Asia,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
Kenya,27,KEN,Nairobi,Africa,5.402749e+07,5.198578e+07,4.685149e+07,4.151790e+07,3.085161e+07,2.316227e+07,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Colombia,28,COL,Bogota,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
South Korea,29,KOR,Seoul,Asia,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
Spain,30,ESP,Madrid,Europe,4.755863e+07,4.736381e+07,4.643134e+07,4.657277e+07,4.074165e+07,3.888989e+07,37491666.0,33792617.0,505992.0,93.9909,1.0015,0.60
Uganda,31,UGA,Kampala,Africa,4.724958e+07,4.440461e+07,3.747736e+07,3.234173e+07,2.402070e+07,1.758663e+07,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Sudan,32,SDN,Khartoum,Africa,4.687420e+07,4.444049e+07,3.817118e+07,3.373993e+07,2.629877e+07,2.109089e+07,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
Argentina,33,ARG,Buenos Aires,South America,4.551032e+07,4.503603e+07,4.325706e+07,4.110012e+07,3.707077e+07,3.263766e+07,28024803.0,23842803.0,2780400.0,16.3683,1.0052,0.57
Algeria,34,DZA,Algiers,Africa,4.490322e+07,4.345167e+07,3.954315e+07,3.585634e+07,3.077462e+07,2.551807e+07,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Iraq,35,IRQ,Baghdad,Asia,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
Afghanistan,36,AFG,Kabul,Asia,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Poland,37,POL,Warsaw,Europe,3.985714e+07,3.842837e+07,3.855315e+07,3.859735e+07,3.850443e+07,3.806426e+07,35521429.0,32482943.0,312679.0,127.4698,1.0404,0.50
Ukraine,38,UKR,Kiev,Europe,3.970174e+07,4.390967e+07,4.498256e+07,4.568302e+07,4.887976e+07,5.158982e+07,49973920.0,47279086.0,603500.0,65.7858,0.9120,0.50
Canada,39,CAN,Ottawa,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
Morocco,40,MAR,Rabat,Africa,3.745797e+07,3.668877e+07,3.468046e+07,3.246486e+07,2.855442e+07,2.457081e+07,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
Saudi Arabia,41,SAU,Riyadh,Asia,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
Angola,42,AGO,Luanda,Africa,3.558899e+07,3.342848e+07,2.812772e+07,2.336418e+07,1.639406e+07,1.182864e+07,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Uzbekistan,43,UZB,Tashkent,Asia,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
Peru,44,PER,Lima,South America,3.404959e+07,3.330476e+07,3.071186e+07,2.922957e+07,2.665444e+07,2.210910e+07,17492406.0,13562371.0,1285216.0,26.4933,1.0099,0.43
Malaysia,45,MYS,Kuala Lumpur,Asia,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
Yemen,46,YEM,Sanaa,Asia,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Ghana,47,GHA,Accra,Africa,3.347587e+07,3.218040e+07,2.887094e+07,2.557472e+07,1.966550e+07,1.544698e+07,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Mozambique,48,MOZ,Maputo,Africa,3.296952e+07,3.117824e+07,NaN,NaN,1.776850e+07,1.330346e+07,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
Nepal,49,NPL,Kathmandu,Asia,3.054758e+07,2.934863e+07,2.761032e+07,2.716157e+07,2.455950e+07,1.961653e+07,15600442.0,12501285.0,147181.0,207.5511,1.0171,0.38
Madagascar,50,MDG,Antananarivo,Africa,2.961171e+07,2.822518e+07,2.485091e+07,2.173105e+07,1.621643e+07,1.188276e+07,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
New Caledonia,185,NCL,Nouméa,Oceania,2.899500e+05,2.864030e+05,2.830320e+05,2.614260e+05,2.215370e+05,1.772640e+05,148599.0,110982.0,18575.0,15.6097,1.0075,0.00
Barbados,186,BRB,Bridgetown,North America,2.816350e+05,2.806930e+05,2.780830e+05,2.747110e+05,2.646570e+05,2.588680e+05,253575.0,241397.0,430.0,654.9651,1.0015,0.00
Sao Tome and Principe,187,STP,São Tomé,Africa,2.273800e+05,2.186410e+05,2.011240e+05,1.821380e+05,1.437140e+05,1.203430e+05,97210.0,77583.0,964.0,235.8714,1.0192,0.00
Samoa,188,WSM,Apia,Oceania,2.223820e+05,2.149290e+05,2.035710e+05,1.946720e+05,1.840080e+05,1.681860e+05,164905.0,142771.0,2842.0,78.2484,1.0165,0.00
Curacao,189,CUW,Willemstad,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
Saint Lucia,190,LCA,Castries,North America,1.798570e+05,1.792370e+05,1.756230e+05,1.709350e+05,1.595000e+05,1.423010e+05,121633.0,103090.0,616.0,291.9756,1.0011,0.00
Guam,191,GUM,Hagåtña,Oceania,1.717740e+05,1.692310e+05,1.679780e+05,1.649050e+05,1.601880e+05,1.382630e+05,110286.0,88300.0,549.0,312.8852,1.0073,0.00
Kiribati,192,KIR,Tarawa,Oceania,1.312320e+05,1.264630e+05,1.167070e+05,1.079950e+05,8.882600e+04,7.512400e+04,60813.0,57437.0,811.0,161.8150,1.0183,0.00
Grenada,193,GRD,Saint George's,North America,1.254380e+05,1.236630e+05,1.189800e+05,1.140390e+05,1.074320e+05,9.904700e+04,94838.0,98794.0,344.0,364.6453,1.0066,0.00
Micronesia,194,FSM,Palikir,Oceania,1.141640e+05,1.121060e+05,1.094620e+05,1.075880e+05,1.117090e+05,9.860300e+04,76299.0,58989.0,702.0,162.6268,1.0091,0.00
Jersey,195,JEY,Saint Helier,Europe,1.107780e+05,1.083190e+05,1.005610e+05,9.615100e+04,8.619200e+04,8.287400e+04,75124.0,68347.0,116.0,954.9828,1.0106,0.00
Seychelles,196,SYC,Victoria,Africa,1.071180e+05,1.055300e+05,9.924000e+04,9.240900e+04,8.006000e+04,7.105700e+04,65290.0,54379.0,452.0,236.9867,1.0061,0.00
Tonga,197,TON,Nuku‘alofa,Oceania,1.068580e+05,1.052540e+05,1.061220e+05,1.073830e+05,1.026030e+05,9.872700e+04,96708.0,86484.0,747.0,143.0495,1.0079,0.00
Aruba,198,ABW,Oranjestad,North America,1.064450e+05,1.065850e+05,1.042570e+05,1.003410e+05,8.910100e+04,6.571200e+04,62267.0,59106.0,180.0,591.3611,0.9991,0.00
Saint Vincent and the Grenadines,199,VCT,Kingstown,North America,1.039480e+05,1.046320e+05,1.064820e+05,1.093080e+05,1.138130e+05,1.124870e+05,107480.0,98459.0,389.0,267.2185,0.9963,0.00
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,9.946500e+04,1.004420e+05,1.028030e+05,1.061420e+05,1.081850e+05,1.006850e+05,96640.0,63446.0,347.0,286.6427,0.9937,0.00
Antigua and Barbuda,201,ATG,Saint John’s,North America,9.376300e+04,9.266400e+04,8.994100e+04,8.569500e+04,7.505500e+04,6.332800e+04,64888.0,64516.0,442.0,212.1335,1.0058,0.00
Isle of Man,202,IMN,Douglas,Europe,8.451900e+04,8.404600e+04,8.359300e+04,8.382800e+04,7.556200e+04,6.886500e+04,64022.0,55298.0,572.0,147.7605,1.0030,0.00
Andorra,203,AND,Andorra la Vella,Europe,7.982400e+04,7.770000e+04,7.174600e+04,7.151900e+04,6.609700e+04,5.356900e+04,35611.0,19860.0,468.0,170.5641,1.0100,0.00
Dominica,204,DMA,Roseau,North America,7.273700e+04,7.199500e+04,7.000700e+04,6.875500e+04,6.834600e+04,6.948100e+04,72978.0,68895.0,751.0,96.8535,1.0045,0.00
Cayman Islands,205,CYM,George Town,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
Bermuda,206,BMU,Hamilton,North America,6.418400e+04,6.403100e+04,6.314400e+04,6.344700e+04,6.137100e+04,5.747000e+04,53565.0,52019.0,54.0,1188.5926,1.0000,0.00
Guernsey,207,GGY,Saint Peter Port,Europe,6.330100e+04,6.279400e+04,6.162900e+04,6.078200e+04,5.911400e+04,5.772700e+04,52860.0,52656.0,78.0,811.5513,1.0037,0.00
Greenland,208,GRL,Nuuk,North America,5.646600e+04,5.602600e+04,5.589500e+04,5.635100e+04,5.618400e+04,5.559900e+04,50106.0,45434.0,2166086.0,0.0261,1.0040,0.00
Faroe Islands,209,FRO,Tórshavn,Europe,5.309000e+04,5.241500e+04,4.881600e+04,4.841000e+04,4.566000e+04,4.747900e+04,43054.0,38416.0,1393.0,38.1120,1.0038,0.00
Northern Mariana Islands,210,NFK,Saipan,Oceania,4.955100e+04,4.958700e+04,5.151400e+04,5.408700e+04,8.033800e+04,4.800200e+04,17613.0,10143.0,464.0,106.7909,1.0014,0.00
Saint Kitts and Nevis,211,KNA,Basseterre,North America,4.765700e+04,4.764200e+04,4.779000e+04,4.740300e+04,4.546100e+04,4.063600e+04,43097.0,44968.0,261.0,182.5939,1.0011,0.00
Turks and Caicos Islands,212,TCA,Cockburn Town,North America,4.570300e+04,4.427600e+04,3.653800e+04,2.972600e+04,1.874400e+04,1.170900e+04,7598.0,5665.0,948.0,48.2099,1.0131,0.00
American Samoa,213,ASM,Pago Pago,Oceania,4.427300e+04,4.618900e+04,5.136800e+04,5.484900e+04,5.823000e+04,4.781800e+04,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Sint Maarten,214,SXM,Philipsburg,North America,4.417500e+04,4.362100e+04,4.020500e+04,3.303400e+04,3.048900e+04,2.784500e+04,12243.0,6260.0,34.0,1299.2647,1.0030,0.00
Marshall Islands,215,MHL,Majuro,Oceania,4.156900e+04,4.341300e+04,4.941000e+04,5.341600e+04,5.422400e+04,4.604700e+04,31988.0,23969.0,181.0,229.6630,0.9886,0.00
Liechtenstein,216,LIE,Vaduz,Europe,3.932700e+04,3.875600e+04,3.735500e+04,3.592600e+04,3.302600e+04,2.876500e+04,25003.0,21089.0,160.0,245.7937,1.0074,0.00
Monaco,217,MCO,Monaco,Europe,3.646900e+04,3.692200e+04,3.676000e+04,3.317800e+04,3.246500e+04,3.032900e+04,27076.0,24270.0,2.0,18234.5000,0.9941,0.00
San Marino,218,SMR,San Marino,Europe,3.366000e+04,3.400700e+04,3.357000e+04,3.160800e+04,NaN,2.313200e+04,21346.0,18169.0,61.0,551.8033,0.9975,0.00
Gibraltar,219,GIB,Gibraltar,Europe,3.264900e+04,3.270900e+04,3.252000e+04,3.126200e+04,2.774100e+04,2.731700e+04,28734.0,26685.0,6.0,5441.5000,0.9994,0.00
Saint Martin,220,MAF,Marigot,North America,3.179100e+04,3.255200e+04,3.502000e+04,3.645800e+04,2.961000e+04,2.812700e+04,7776.0,5802.0,53.0,599.8302,0.9951,0.00
British Virgin Islands,221,VGB,Road Town,North America,3.130500e+04,3.091000e+04,2.936600e+04,2.755600e+04,2.010400e+04,1.561700e+04,11109.0,9581.0,151.0,207.3179,1.0059,0.00
Palau,222,PLW,Ngerulmud,Oceania,NaN,1.797200e+04,1.779400e+04,1.854000e+04,1.972600e+04,1.529300e+04,12252.0,11366.0,459.0,39.3355,1.0017,0.00
Cook Islands,223,COK,Avarua,Oceania,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00
Anguilla,224,AIA,The Valley,North America,1.585700e+04,1.558500e+04,1.452500e+04,1.317200e+04,1.104700e+04,8.316000e+03,6560.0,6283.0,91.0,174.2527,1.0066,0.00
Nauru,225,NRU,Yaren,Oceania,1.266800e+04,1.231500e+04,1.118500e+04,1.024100e+04,1.037700e+04,9.598000e+03,7635.0,6663.0,21.0,603.2381,1.0125,0.00
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,1.157200e+04,1.165500e+04,1.218200e+04,1.314200e+04,1.472300e+04,1.345400e+04,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Tuvalu,227,TUV,Funafuti,Oceania,1.131200e+04,1.106900e+04,1.087700e+04,1.055000e+04,9.638000e+03,9.182000e+03,7731.0,5814.0,26.0,435.0769,1.0096,0.00
Saint Barthelemy,228,BLM,Gustavia,North America,1.096700e+04,1.068100e+04,9.643000e+03,8.988000e+03,7.082000e+03,5.168000e+03,2983.0,2417.0,21.0,522.2381,1.0098,0.00
Saint Pierre and Miquelon,229,SPM,Saint-Pierre,North America,5.862000e+03,5.906000e+03,5.978000e+03,6.052000e+03,6.274000e+03,6.324000e+03,6106.0,5537.0,242.0,24.2231,0.9964,0.00
Montserrat,230,MSR,Brades,North America,4.390000e+03,4.500000e+03,5.059000e+03,4.938000e+03,5.138000e+03,1.080500e+04,11452.0,11402.0,102.0,43.0392,0.9939,0.00
Falkland Islands,231,FLK,Stanley,South America,3.780000e+03,3.747000e+03,3.408000e+03,3.187000e+03,3.080000e+03,2.332000e+03,2240.0,2274.0,12173.0,0.3105,1.0043,0.00
Niue,232,NIU,Alofi,Oceania,1.934000e+03,1.942000e+03,1.847000e+03,1.812000e+03,2.074000e+03,2.533000e+03,3637.0,5185.0,260.0,7.4385,0.9985,0.00
Tokelau,233,TKL,Nukunonu,Oceania,1.871000e+03,1.827000e+03,1.454000e+03,1.367000e+03,1.666000e+03,1.669000e+03,1647.0,1714.0,12.0,155.9167,1.0119,0.00
Vatican City,234,VAT,Vatican City,Europe,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,733.0,752.0,1.0,510.0000,0.9980,0.00